site_name: ScriptBlocks.py
theme:
  name: material
  palette:
    - scheme: dark
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant

nav:
  - Introduction: index.md
  - Volume 1 - Getting Started:
    - Creating your first app: vol1/chap1.md